### ISSUE TITLE
Hey this seemed to be the best way to get in touch with you

### ISSUE THREAD

**Issue by sonshogun** [bfay1/osvm-dotfiles#1]
For some reason your job interview traffic is coming to my inbox - I've got brendan DOT fay at gmail. You got a second round interview too - wanted to know where to forward the information. Let me know if you have a correct email for them

**Comment by bfay1** [comment]
Which company and how much traffic? This is actually really distressing...

**Comment by sonshogun** [comment]
Nothing too catastrophic - I just noticed recently I'd been getting a few thanks for your interests in companies I hadn't expressed ( not looking at the moment ) and then a search found a response to one with this git hub - let me forward everything I can find to you - also I could setup a zoom to run though searches if you think of a couple more.

**Comment by sonshogun** [comment]
Forwarded everything I could find that seemed relevant - let me know if you want me to check any others, from the Tokyodev where I got your git it lists my email, so I'd think everything out of there is a likely suspect to get back through to me. The last forward chronologically has that full application in it's signature.

**Comment by bfay1** [comment]
Thank you so much! I really appreciate it. The only other one that I would be curious about would be Snowflake.
Super fortuitous that brendan.fay@gmail.com belongs to a github user lol

**Comment by sonshogun** [comment]
No worries! Programmers named Brendan Fay in the Tri-state area have to look out for one another. Nothing on Snowflake from my end except mentions in tech newsletters etc. Yeah I was amused at the coincidence - not sure how I could have got in touch with a sales rep etc with similar issue. Best of luck on the job hunt, it's a rough market these days so don't get discouraged either way.

**Comment by bfay1** [comment]
Thanks so much, I really appreciate it!
